-- 1. Add `in_poll` column to `tidc_results`
ALTER TABLE tidc_results ADD COLUMN in_poll boolean DEFAULT false;

-- 2. Create the `tidc_votes` table
CREATE TABLE IF NOT EXISTS tidc_votes (
  id bigint generated by default as identity primary key,
  category text not null,
  candidate_name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable RLS and setup policies for `tidc_votes`
ALTER TABLE tidc_votes ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read the votes (so the public poll page can count them)
CREATE POLICY "Allow public read access to votes"
  ON tidc_votes FOR SELECT
  USING (true);

-- Allow anyone to insert a vote
CREATE POLICY "Allow public insert to votes"
  ON tidc_votes FOR INSERT
  WITH CHECK (true);

-- Allow authenticated users to delete votes (admin cleanup if needed)
CREATE POLICY "Allow authenticated delete from votes"
  ON tidc_votes FOR DELETE
  USING (auth.role() = 'authenticated');
