-- Schema for TIDC 2026 Supabase Database

-- 1. Results Table (tidc_results)
-- Stores the list of qualified students, runners-up, winners, and special mentions for each category and round.
create table if not exists tidc_results (
  id bigint generated by default as identity primary key,
  registration_id bigint references tidc_registrations(id) on delete cascade,
  student_name text not null,
  bace text,
  category text not null,
  round text not null default 'Round 2',
  status text not null default 'Qualified',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) for tidc_results
alter table tidc_results enable row level security;

-- Policies for tidc_results
create policy "Allow public read access to results"
  on tidc_results for select
  using (true);

create policy "Allow authenticated insert to results"
  on tidc_results for insert
  with check (auth.role() = 'authenticated');

create policy "Allow authenticated delete from results"
  on tidc_results for delete
  using (auth.role() = 'authenticated');


-- 2. Settings Table (tidc_settings)
-- Stores database-backed configuration variables (like registration_deadline).
create table if not exists tidc_settings (
  key text primary key,
  value text not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) for tidc_settings
alter table tidc_settings enable row level security;

-- Policies for tidc_settings
create policy "Allow public read access to settings"
  on tidc_settings for select
  using (true);

create policy "Allow authenticated write access to settings"
  on tidc_settings for all
  using (auth.role() = 'authenticated');

-- Initialize default registration closing deadline (Format: YYYY-MM-DDTHH:mm:ss)
insert into tidc_settings (key, value)
values ('registration_deadline', '2026-06-15T23:59:59')
on conflict (key) do update set value = excluded.value;
